version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
    networks:
      - docuparse-network
    depends_on:
      - backend-core

  backend-core:
    build: ./backend-core
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend-core:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - docuparse-network
    depends_on:
      - backend-ocr

  backend-ocr:
    build: ./backend-ocr
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./backend-ocr:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - docuparse-network

networks:
  docuparse-network:
    driver: bridge
